name: plant_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_bottom_navigation_bar: ^1.3.0
  page_transition: ^2.1.0  
  flutter_native_splash: ^2.3.4

flutter_native_splash:
  color: "#77d353"
  image: assets/images/plante.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  background_color: "77d353"
  image_path: "assets/images/plante.png"
  android: true


flutter:
  uses-material-design: true
  assets:
     - assets/images/
